#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^[a-z0-9-]+$"

message="Error: Invalid branch name. Branch names can only contain lowercase letters, numbers, and dashes. Your commit will be rejected. You have to rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
	echo "$message"
	exit 1
fi

exit 0
