#!/bin/sh

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^[a-z0-9-]+$"

message="Error: Invalid branch name. Branch names can only contain lowercase letters, numbers, and dashes. Your commit will be rejected. You have to rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
	echo "$message"
	exit 1
fi

exit 0
