nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'linux'
    - 'darwin'
    - 'win32'
  cpu:
    - 'current'
    - 'x64'
    - 'arm64'

logFilters:
  - code: YN0002
    level: discard
