export default {
  modules: [
    '@storefront-x/base',

    '@storefront-x/vue',
    '@storefront-x/vue-router',
    '@storefront-x/vue-head',
    '@storefront-x/vue-i18n',
    '@storefront-x/vue-pinia',

    '@storefront-x/base-commerce',
    '@storefront-x/atomic-design',
    '@storefront-x/graphql',
    '@storefront-x/cypress',

    '@storefront-x/blog',
    '@storefront-x/braintree',
    '@storefront-x/brands',
    '@storefront-x/cart',
    '@storefront-x/catalog',
    '@storefront-x/checkout',
    '@storefront-x/cms',
    '@storefront-x/customer',
    '@storefront-x/free-shipping',
    '@storefront-x/multicurrency',
    '@storefront-x/product-reviews',
    '@storefront-x/wishlist',
    '@storefront-x/catalog-labels',
    '@storefront-x/robots',

    '@storefront-x/magento',
    '@storefront-x/blog-magento',
    '@storefront-x/braintree-magento',
    '@storefront-x/brands-magento',
    '@storefront-x/cart-magento',
    '@storefront-x/catalog-magento',
    '@storefront-x/catalog-magento-px',
    '@storefront-x/checkout-magento',
    '@storefront-x/cms-magento',
    '@storefront-x/customer-magento',
    '@storefront-x/free-shipping-magento',
    '@storefront-x/multicurrency-magento',
    '@storefront-x/product-reviews-magento',
    '@storefront-x/wishlist-magento',
    '@storefront-x/catalog-labels-magento',
    '@storefront-x/robots-magento',

    '@storefront-x/theme-tailwind',
    '@storefront-x/theme-tailwind-magento',

    '@storefront-x/demo-magento',
  ],
}
