//@ts-check

import { GeneratingConcept } from '@storefront-x/core'

export default class GlobalStyles extends GeneratingConcept {
  get directory() {
    return 'global/styles'
  }

  get recursive() {
    return true
  }

  get template() {
    return `// generated by Storefront X
<%_ for (const item in records) { _%>
import <%= records[item].importName %> from '<%= records[item].filePath %>?inline'
<%_ } _%>

export default {
<%_ for (const [ident, {importName}] of Object.entries(records)) { _%>
  '<%= ident %>': <%= importName %>,
<%_ } _%>
}
`
  }
}
