//@ts-check

import { GeneratingConcept } from '@storefront-x/core'

export default class ServerStartup extends GeneratingConcept {
  get directory() {
    return 'server/startup'
  }

  get template() {
    return `// generated by Storefront X
<%_ for (const item in records) { _%>
import '<%= records[item].filePath %>'
<%_ } _%>

// Supress warnings about empty chunks
export default {}
`
  }
}
