//@ts-check

import { GeneratingConcept } from '@storefront-x/core'

export default class Tests extends GeneratingConcept {
  get directory() {
    return 'tests/unit'
  }
  get generateMultipleFiles() {
    return true
  }
  get template() {
    return `// generated by Storefront X
    import '<%= record.path %>'
`
  }
}
