import { MergingConcept } from '@storefront-x/core'

export default class BusListeners extends MergingConcept {
  get directory() {
    return 'bus/listeners'
  }

  get template() {
    return `// generated by Storefront X
<%_ for (const group of Object.values(records)) { _%>
<%_ for (const item of group) { _%>
import <%= item.importName %> from '<%= item.path %>'
<%_ } _%>
<%_ } _%>

const obj: Record<string, any> = {}

<%_ for (const [ident, group] of Object.entries(records)) { _%>
obj['<%= ident %>'] = [
<%_ for (const item of group) { _%>
<%= item.importName %>,
<%_ } _%>
]

<%_ } _%>
export default obj
`
  }
}
