export default {
  HOMEPAGE: 'home-page',
  PRODUCT: 'product-detail-page',
  CATEGORY: 'category-detail-page',
  CMS_PAGE: 'cms-page',
  AMASTY_BRAND: 'brand-detail-page',
  AMASTY_BLOG_POST: 'blog-post-detail-page',
  AMASTY_BLOG_CATEGORY: 'blog-category-detail-page',
  WISHLIST: 'wishlist-page',
  CHECKOUT: 'checkout-page',
  ACCOUNT: 'account-page',
  SIGN_IN: 'sign-in-page',
  SIGN_UP: 'sign-up-page',
  SEARCH: 'search-page',
  RESET_PASSWORD: 'reset-password-page',
} as const
