export default {
  modules: [
    '@magexo/base',

    '@magexo/vue',
    '@magexo/vue-router',
    '@magexo/vue-head',
    '@magexo/vue-i18n',
    '@magexo/vue-pinia',
    '@magexo/vue-pinia-shared-state',

    '@magexo/base-commerce',
    '@magexo/atomic-design',
    '@magexo/graphql',
    '@magexo/cypress',
    '@magexo/schema-org',
    '@magexo/nprogress',
    '@magexo/service-worker',
    '@magexo/web-app-manifest',
    '@magexo/runtime-config',
    '@magexo/flash-messages',
    '@magexo/build-time-version',
    ...(process.env.NODE_ENV === 'development' ? ['@magexo/request-profiler'] : []),

    '@magexo/magento',

    '@magexo/blog',
    '@magexo/braintree',
    '@magexo/brands',
    '@magexo/cart',
    '@magexo/catalog',
    '@magexo/checkout',
    '@magexo/cms',
    '@magexo/customer',
    '@magexo/free-shipping',
    '@magexo/multicurrency',
    '@magexo/product-reviews',
    '@magexo/wishlist',
    '@magexo/catalog-labels',
    '@magexo/product-comparison',
    '@magexo/robots',
    '@magexo/sitemap',
    '@magexo/speed-curve',

    '@magexo/blog-magento',
    '@magexo/braintree-magento',
    '@magexo/brands-magento',
    '@magexo/cart-magento',
    '@magexo/catalog-magento',
    '@magexo/catalog-magento-px',
    '@magexo/checkout-magento',
    '@magexo/checkout-magento-px',
    '@magexo/cms-magento',
    '@magexo/customer-magento',
    '@magexo/catalog-attributes-magento',
    '@magexo/free-shipping-magento',
    '@magexo/multicurrency-magento',
    '@magexo/product-reviews-magento',
    '@magexo/wishlist-magento',
    '@magexo/catalog-labels-magento',
    '@magexo/product-comparison-magento',
    '@magexo/robots-magento',
    '@magexo/sitemap-magento',
    '@magexo/newsletter-magento',

    '@magexo/theme-tailwind',
    '@magexo/theme-tailwind-magento',
    '@magexo/theme-tailwind-magento-px',

    'demo-px',
  ],
}
