export default {
  modules: [
    '@storefront-x/base',

    '@storefront-x/vue',
    '@storefront-x/vue-router',
    '@storefront-x/vue-head',
    '@storefront-x/vue-i18n',
    '@storefront-x/vue-pinia',
    '@storefront-x/vue-pinia-shared-state',

    '@storefront-x/base-commerce',
    '@storefront-x/atomic-design',
    '@storefront-x/graphql',
    '@storefront-x/cypress',
    '@storefront-x/schema-org',
    '@storefront-x/nprogress',
    '@storefront-x/service-worker',
    '@storefront-x/web-app-manifest',
    '@storefront-x/runtime-config',
    '@storefront-x/flash-messages',
    '@storefront-x/build-time-version',
    ...(process.env.NODE_ENV === 'development' ? ['@storefront-x/request-profiler'] : []),

    '@storefront-x/magento',

    '@storefront-x/blog',
    '@storefront-x/braintree',
    '@storefront-x/brands',
    '@storefront-x/cart',
    '@storefront-x/catalog',
    '@storefront-x/checkout',
    '@storefront-x/cms',
    '@storefront-x/customer',
    '@storefront-x/free-shipping',
    '@storefront-x/multicurrency',
    '@storefront-x/product-reviews',
    '@storefront-x/wishlist',
    '@storefront-x/catalog-labels',
    '@storefront-x/product-comparison',
    '@storefront-x/robots',
    '@storefront-x/sitemap',
    '@storefront-x/speed-curve',

    '@storefront-x/blog-magento',
    '@storefront-x/braintree-magento',
    '@storefront-x/brands-magento',
    '@storefront-x/cart-magento',
    '@storefront-x/catalog-magento',
    '@storefront-x/catalog-magento-px',
    '@storefront-x/checkout-magento',
    '@storefront-x/checkout-magento-px',
    '@storefront-x/cms-magento',
    '@storefront-x/customer-magento',
    '@storefront-x/catalog-attributes-magento',
    '@storefront-x/free-shipping-magento',
    '@storefront-x/multicurrency-magento',
    '@storefront-x/product-reviews-magento',
    '@storefront-x/wishlist-magento',
    '@storefront-x/catalog-labels-magento',
    '@storefront-x/product-comparison-magento',
    '@storefront-x/robots-magento',
    '@storefront-x/sitemap-magento',
    '@storefront-x/newsletter-magento',

    '@storefront-x/theme-tailwind',
    '@storefront-x/theme-tailwind-magento',
    '@storefront-x/theme-tailwind-magento-px',

    'demo-px',
  ],
}
