//@ts-check

import { GeneratingConcept } from '@storefront-x/core'

export default class Sitemap extends GeneratingConcept {
  get directory() {
    return 'sitemap'
  }

  get exportAll() {
    return true
  }

  get template() {
    return `// generated by Storefront X
<%_ for (const item in records) { _%>
import <%= records[item].importName %> from '<%= records[item].path %>'
<%_ } _%>

export default {
<%_ for (const [ident, {importName}] of Object.entries(records)) { _%>
    <%= importName %>,
<%_ } _%>
}
`
  }
}
