name: Yarn build

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Remove unused cache
        uses: skjolber/tidy-cache-github-action@v1
      - name: Install dependencies
        run: yarn build --config storefront-x.${{inputs.storefront-x-config}}.config.js
      - name: Save built .sfx directory to cache
        uses: actions/cache/save@v3
        with:
          path: .sfx
          key: ${{ runner.os }}-sfx-${{inputs.storefront-x-config}}
