name: Create script

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: create-script-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yarn:
    strategy:
      matrix:
        integration: [magento, shopware, venia]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn create storefront-x --directory=app --integration=${{ matrix.integration }}
          cd app
          yarn install
          yarn build
  npm:
    strategy:
      matrix:
        integration: [magento, shopware, venia]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm create storefront-x@latest -y -- --directory=app --integration=${{ matrix.integration }}
          cd app
          npm install
          npm run build
