name: Performance audit

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string
      product-detail-page:
        required: true
        type: string
      category-page:
        required: true
        type: string

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore cached node_modules
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: npm install -g @lhci/cli@0.9.x
      - name: Restore cached .sfx directory
        uses: actions/cache/restore@v3
        with:
          path: .sfx
          key: ${{ runner.os }}-sfx-${{inputs.storefront-x-config}}
      - run: >
          lhci collect --startServerCommand "yarn serve --compression"
          --url http://localhost:3000
          --url http://localhost:3000/${{ inputs.product-detail-page }}
          --url http://localhost:3000/${{ inputs.category-page }}
      - run: lhci upload
      - run: lhci assert
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
