name: Performance audit

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.2
        with:
          url: "https://magento.storefrontx.io/"
          threshold: 80
          strategy: mobile
          key: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
