name: Performance audit

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse
    steps:
      - name: Homepage page
        uses: jakepartusch/psi-action@v1.2
        with:
          url: "https://magento.storefrontx.io/"
          threshold: 85
          strategy: mobile
          key: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Product detail page
        uses: jakepartusch/psi-action@v1.2
        with:
          url: "https://magento.storefrontx.io/dnp-ds820-professional-photo-printer.html"
          threshold: 85
          strategy: mobile
          key: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

