name: Performance audit

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string
      homepage:
        required: true
        type: string
      product-detail-page:
        required: true
        type: string

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g @lhci/cli@0.6.x
      - run: yarn && yarn build --config ${{inputs.storefront-x-configinputs.storefront-x-config}}
      - run: lhci collect --startServerCommand yarn serve --url ${{inputs.storefront-x-config}}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
