name: MxCloud

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string
    secrets:
      MXCLOUD_URL:
        required: true
      MXCLOUD_AUTH:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  mxcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: mxcloud/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SFX_CONFIG=${{ inputs.storefront-x-config }}

      - name: Deploy to MxCloud
        shell: bash
        run: >
          ENV_DEPLOY_SUCCESS=false

          for i in $(seq 1 3); do
            echo "Deploying '$BUILD_TAG' to $MXCLOUD_DEPLOY_API_DOMAIN attemp no. ${i}"

            curl --fail -L --max-time 120 --retry 5 --request POST ${{ secrets.MXCLOUD_URL }}/api/env/deploy
            --header 'Authorization: Basic ${{ secrets.MXCLOUD_AUTH }}'
            --header 'Content-Type: application/json'
            --data-raw '{
            "git_project": "storefront-x",
            "git_branch": "${{ github.ref_name }}",
            "commit_ref": "${{ github.sha }}",
            "env_vars": {
            "DEPLOY_TYPE": "deploy",
            "CI_REGISTRY": "${{ env.REGISTRY }}",
            "CI_REPOSITORY_URL": "git@github.com:storefront-x/storefront-x.git",
            "PROJECT_NAME": "storefront-x",
            "BUILD_TAG": "${{ github.ref_name }}",
            "CI_REPOSITORY": "${{ env.IMAGE_NAME }}"
            }
            }' || (echo "Deploying request failed, retrying in 20 seconds ..." && sleep 20 && continue)

            ENV_DEPLOY_SUCCESS=true
            break
          done

          if [ "$ENV_DEPLOY_SUCCESS" = false ]; then
            echo "Deploy env request failed 3 times, exiting"
            exit 1
          fi
