name: Playwright

on:
  workflow_call:
    inputs:
      number-of-tests-per-run:
        default: 3
        type: number
      target-directory:
        default: modules/**/tests/playwright
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        count: $(echo '[$(seq -s , 1 ${{ inputs.number-of-tests-per-run }})]' | jq -c '.')
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - setup
    name: test ${{ env.MATRIX_INDEX }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --immutable --immutable-cache
      - run: npx playwright install chromium
      - run: npx playwright test --shard=${{ env.MATRIX_INDEX }}/${{ env.MATRIX_SIZE }} --forbid-only
