name: Playwright

on:
  workflow_call:
    inputs:
      number-of-shard:
        default: 3
        type: number

jobs:
  setup: # This job is needed to set the matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-array: ${{ steps.generate-matrix-array.outputs.matrix-array }}
    steps:
      - id: generate-matrix-array
        run: echo "matrix-array=$(echo \$(seq 1 ${{ inputs.number-of-shard }} | jq -cM 'map(tonumber)'))" >> $GITHUB_OUTPUT

  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        count: ${{ fromJSON(needs.setup.outputs.matrix-array) }}
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test ${{ matrix.count }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --immutable --immutable-cache
      - run: npx playwright install chromium
      - run: npx playwright test --shard=${{ matrix.count }}/${{ inputs.number-of-shard }} --forbid-only
