name: Playwright

on:
  workflow_call:
    inputs:
      number-of-tests-per-run:
        default: 3
        type: number
      target-directory:
        default: modules/**/tests/playwright
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    outputs:
      # json string with ids to use in the next job matrix depending on how many elements are in the above array, eg: [0,1]
      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
    steps:
      - id: set-test-chunk-ids
        name: Set Chunk IDs
        run: echo "test-chunk-ids=$(echo "[$(seq -s , 1 ${{ inputs.number-of-tests-per-run }} | tr '\n' ',' | sed 's/,$//')]" | jq -cM 'map(tonumber)')" >> $GITHUB_OUTPUT

  test:
    strategy:
      fail-fast: false
      matrix:
        chunk: ${{fromJSON(needs.setup.outputs['test-chunk-ids'])}}
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - setup
    name: chunk ${{ matrix.chunk }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --immutable --immutable-cache
      - run: npx playwright install chromium
      - run: npx playwright test --shard=${{ matrix.chunk }}/${{ inputs.number-of-tests-per-run }} --forbid-only
