name: PX

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{github.ref }}-${{ github.job }}
  cancel-in-progress: ${{ github.sha != github.event.before }}

jobs:
  yarn:
    uses: ./.github/workflows/yarn.yml
    with:
      os: ubuntu-latest

  lint:
    needs: [yarn]
    uses: ./.github/workflows/lint.yml
    with:
      storefront-x-config: storefront-x.px.config.js

  unit:
    needs: [yarn]
    uses: ./.github/workflows/unit.yml
    with:
      storefront-x-config: storefront-x.px.config.js

  cypress:
    needs: [yarn]
    uses: ./.github/workflows/cypress.yml
    with:
      storefront-x-config: storefront-x.px.config.js
      number-of-tests-per-run: 3
      target-directory: cypress/e2e

  mxcloud:
    uses: ./.github/workflows/mxcloud.yml
    with:
      storefront-x-config: storefront-x.px.config.js
    secrets:
      MXCLOUD_URL: ${{ secrets.MXCLOUD_URL }}
      MXCLOUD_AUTH: ${{ secrets.MXCLOUD_AUTH }}

  lighthouse:
    needs: [yarn]
    uses: ./.github/workflows/lighthouse.yml
    with:
      storefront-x-config: storefront-x.px.config.js
      product-detail-page: tripp-lite-n238-001-yw-keystone-module.html
      category-page: computers-peripherals.html
