name: PX

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{github.ref }}-${{ github.job }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  yarn:
    uses: ./.github/workflows/yarn.yml
    with:
      os: ubuntu-latest

  lint:
    needs: [yarn]
    uses: ./.github/workflows/lint.yml
    with:
      storefront-x-config: storefront-x.aero.config.js
  mxcloud:
    uses: ./.github/workflows/mxcloud.yml
    with:
      storefront-x-config: storefront-x.aero.config.js
    secrets:
      MXCLOUD_URL: ${{ secrets.MXCLOUD_URL }}
      MXCLOUD_AUTH: ${{ secrets.MXCLOUD_AUTH }}
