name: Setup Cypress

on:
  workflow_call:
    inputs:
      number-of-tests-per-run:
        default: 3
        type: number
      target-directory:
        default: cypress/integration
        type: string
    outputs:
      test-chunks:
        description: 'will contain a json string with an array of n elements, each being a string of spec files delimited by ,'
        value: ${{ jobs.setup.outputs['setup-test-chunks'] }}
      test-chunk-ids:
        description: 'json string with ids to use in the next job matrix depending on how many elements are in the above array, eg: [0,1]'
        value: ${{ jobs.setup.outputs['setup-test-chunk-ids'] }}

jobs:
  setup-cypress:
    runs-on: ubuntu-latest
    name: Setup Cypress
    outputs:
      setup-test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
      setup-test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        name: Build app
      - run: yarn install
      - run: yarn build --config storefront-x.magento.config.js --onlyBootstrap
      - id: set-test-chunks
        name: Set Chunks
        # get all spec files from the target-directory directory, group them to be at most number-of-tests-per-run (xargs -n...) at a time and transform them to json
        run: echo "::set-output name=test-chunks::$(find ${{inputs.target-directory}} -type f -name "*.js" | xargs -n${{inputs.number-of-tests-per-run}} | tr ' ' ',' | jq -R . | jq -s -cM .)"
      - id: set-test-chunk-ids
        name: Set Chunk IDs
        # get the number of elements from the above array as an array of indexes
        run: echo "::set-output name=test-chunk-ids::$(echo '${{ steps['set-test-chunks'].outputs['test-chunks'] }}' | jq -cM 'to_entries | map(.key)')"
