name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build --onlyBootstrap
      - run: yarn lint
  typescript:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build --onlyBootstrap
      - run: yarn tsc --noEmit
  unit:
    runs-on: ubuntu-latest
    name: Unit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build --onlyBootstrap
      - run: yarn test:unit
  playwright:
    runs-on: ubuntu-latest
    name: Playwright
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn playwright install chromium
      - run: yarn test:playwright
