name: Unit

on:
  workflow_call:
    inputs:
      storefront-x-config:
        required: true
        type: string

concurrency:
  group: ${{ github.ref != 'refs/heads/main' && github.workflow + '-' + github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore cached node_modules
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn build --config ${{ inputs.storefront-x-config }} --onlyBootstrap
      - run: yarn test:unit
