name: yarn

on:
  workflow_call:
    inputs:
      os:
        required: true

jobs:
  # This job will cache yarn dependencies when they already not exist in cache. If exists, it will restore them
  # without having to install them in each job (which takes a lot of time)
  # They are stored by hash of the yarn.lock file, so they will be invalidated if the dependencies themselves change
  yarn:
    strategy:
      matrix:
        os: ${{ inputs.os }}
    runs-on: ${{ matrix.os }}
    name: yarn install (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules from cache
        id: cache-nodemodules
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache
      - name: Save node_modules to cache
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
