import path from 'node:path'
import { GeneratingConcept } from '@storefront-x/core'
import fs from 'node:fs/promises'

export default class CypressIntegration extends GeneratingConcept {
  async before() {
    await this.clearCypressDir()
    await fs.mkdir(this.dst(), { recursive: true })
  }

  get directory() {
    return 'cypress/integration'
  }

  get extension() {
    return 'js'
  }

  get generateMultipleFiles() {
    return true
  }

  dst() {
    return path.join(this.core.rootDir, this.directory)
  }

  get template() {
    return `// generated by Storefront X
import '<%= record.path %>'
`
  }

  async clearCypressDir() {
    await fs.rm(this.cypressDir, { recursive: true, force: true })
  }

  get cypressDir() {
    return path.resolve(this.core.rootDir, this.directory)
  }
}
