//@ts-check

import { GeneratingConcept } from '@storefront-x/core'
import path from 'node:path'

export default class CypressPlugins extends GeneratingConcept {
  get directory() {
    return 'cypress/plugins'
  }

  get template() {
    return `// generated by Storefront X
/// <reference types="cypress" />

<%_ for (const item in records) { _%>
import ${
      this.exportAll ? '* as <%= records[item].importName %>' : '<%= records[item].importName %>'
    } from '<%= records[item].path %>'
<%_ } _%>

/**
 * @type {Cypress.PluginConfig}
 */
export default (on: any, config: any) => {
<%_ for (const [_, {importName}] of Object.entries(records)) { _%>
  <%= importName %>(on, config)
<%_ } _%>
}
`
  }

  dst() {
    return path.join(this.core.rootDir, this.directory)
  }

  get fileName() {
    return 'index.ts'
  }
}
