//@ts-check

import { GeneratingConcept } from '@storefront-x/core'
import path from 'node:path'

export default class CypressSupport extends GeneratingConcept {
  get directory() {
    return 'cypress/support'
  }

  get template() {
    return `// generated by Storefront X

    <%_ for (const item in records) { _%>
import '<%= records[item].path %>'
<%_ } _%>
`
  }

  dst() {
    return path.join(this.core.rootDir, this.directory)
  }

  get fileName() {
    return 'index.ts'
  }
}
