//@ts-check

import { GeneratingConcept } from '@storefront-x/core'
import path from 'node:path'

export default class CypressCommands extends GeneratingConcept {
  get directory() {
    return 'cypress/commands'
  }

  get template() {
    return `// generated by Storefront X
<%_ for (const item in records) { _%>
import '<%= records[item].path %>'
<%_ } _%>
`
  }

  dst() {
    return path.join(this.core.rootDir, 'cypress', 'support')
  }
}
