//@ts-check

import { GeneratingConcept } from '@storefront-x/core'
import path from 'node:path'
import fs from 'node:fs/promises'

export default class CypressSupport extends GeneratingConcept {
  async before() {
    await this.clearCypressDir()
    await fs.mkdir(this.dst(), { recursive: true })
  }

  get directory() {
    return 'cypress/commands'
  }

  get template() {
    return `// generated by Storefront X

    <%_ for (const item in records) { _%>
import '<%= records[item].path %>'
<%_ } _%>
`
  }

  dst() {
    return path.join(this.core.rootDir, 'cypress/support')
  }

  get fileName() {
    return 'index.ts'
  }

  async clearCypressDir() {
    await fs.rm(this.cypressDir, { recursive: true, force: true })
  }

  get cypressDir() {
    return path.resolve(this.core.rootDir, 'cypress/support')
  }
}
