import path from 'node:path'
import { GeneratingConcept } from '@storefront-x/core'

export default class CypressIntegration extends GeneratingConcept {
  get directory() {
    return 'cypress/e2e'
  }

  get extension() {
    return 'js'
  }

  get generateMultipleFiles() {
    return true
  }

  get removesDestinationDirectory() {
    return true
  }

  dst() {
    return path.join(this.core.rootDir, this.directory)
  }

  get template() {
    return `// generated by Storefront X
import '<%= record.filePath %>'
`
  }
}
