import path from 'node:path'
import { GeneratingConcept } from '@storefront-x/core'

export default class CypressRepoitories extends GeneratingConcept {
  get directory() {
    return 'cypress/support/repositories'
  }

  get extension() {
    return 'js'
  }

  get generateMultipleFiles() {
    return true
  }

  dst() {
    return path.join(this.core.rootDir, this.directory)
  }

  get template() {
    return `// generated by Storefront X
import <%= record.importName %> from '<%= record.path %>'

export default <%= record.importName %>
`
  }
}
